Code for HW 2


In [1]:
import numpy as np 

Q4


In [6]:
v0 = np.array([0.5, 0.5, 0.5, 0.5]).T
v1 = np.array([0.5, 0.5, -0.5, -0.5]).T
v2 = np.array([0.5, -0.5, 0.5, -0.5]).T

In [8]:
A = 0.5*np.matrix([[1, 1, 1, 1],[1, 1, -1 ,-1],[1, -1, 1, -1]])

In [15]:
y = np.matrix([-0.5, 0.5, 0.5, 1.5]).T

In [17]:
from sympy import *

In [41]:
a, b, c, d = symbols('a b c d')
v3 = np.array([a, b, c, d])
answer = solve([v0.dot(v3), v1.dot(v3), v2.dot(v3), v3.dot(v3)-1], (a, b, c, d))

In [60]:
q1 = np.asarray(answer[0], dtype='float')
q2 = np.asarray(answer[1], dtype='float')

print(q1)
print('------------')
print(q2)

[-0.5  0.5  0.5 -0.5]
------------
[ 0.5 -0.5 -0.5  0.5]


In [61]:
A1 = np.stack((v0, v1, v2,q1),axis = -1)

print(A1)

[[ 0.5  0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5 -0.5]]


In [62]:
A2 = np.stack((v0, v1, v2, q2),axis = -1)

print(A2)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


y = Ac

c = inv(C)*y

In [63]:
from numpy import linalg as la

In [64]:
print("Shape of A matrix: ",A1.shape)

print("Shape of y: ", y.shape)

Shape of A matrix:  (4, 4)
Shape of y:  (4, 1)


Evaluating the coefficients needed to produce y give the bases matrix A1 and A2

In [70]:
A1_prime = la.inv(A1)
print(np.dot(A1_prime,y))

[[ 1.]
 [-1.]
 [-1.]
 [ 0.]]


In [71]:
A2_prime = la.inv(A2)
print(np.dot(A2_prime,y))

[[ 1.]
 [-1.]
 [-1.]
 [ 0.]]


## Q4

In [83]:
y = np.reshape(y, (4,1))

In [85]:
q1 = np.reshape(q1, (4,1))
q2 = np.reshape(q2, (4,1))

In [88]:
v0 = np.reshape(v0, (4,1))
v1 = np.reshape(v1, (4,1))
v2 = np.reshape(v2, (4,1))

In [98]:
Q1 = np.hstack((y,v1,v2,q1))
print(la.matrix_rank(Q1))

4


In [99]:
Q2 = np.hstack((y,v0,v2,q1))
print(la.matrix_rank(Q2))

4


In [100]:
Q3 = np.hstack((y,v0,v1,v2))
print(la.matrix_rank(Q3))

3


In [101]:
Q4 = np.hstack((y,v1,v2,q1-2*v1))
print(la.matrix_rank(Q4))

4


Select option 1,2 and 4